import { Geist, Geist_Mono, Xanh_Mono , Plus_Jakarta_Sans ,Space_Grotesk} from "next/font/google";
import { Outfit } from "next/font/google";

import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const space = Space_Grotesk({
  subsets:["latin"]
})
const Plus=Plus_Jakarta_Sans({
  subsets:["latin"]
})
const Xanh = Xanh_Mono({
  weight: ["400"],
  subsets: ["latin"],
});
const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500"],
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${space.className} antialiased dark selection:bg-[#2058f9] selection:text-white`}>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
